export const toolbarStyles = theme => ({
  toolbarContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 24px',
    minHeight: '70px',
    width: '100%',
    boxSizing: 'border-box',
  },
  logoContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'transform 0.3s ease',
    '&:hover': {
      transform: 'scale(1.02)',
    },
  },
  draggableNodesContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    justifyContent: 'center',
    flexGrow: 1,
    flexWrap: 'nowrap',
  },
  commonNodeStyles: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '16px',
    borderRadius: '10px',
    color: '#fff',
    padding: '10px 18px',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    position: 'relative',
    fontWeight: 500,
    letterSpacing: '0.3px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    '&:hover': {
      backgroundColor: theme.palette.secondary.main,
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 8px rgba(0, 0, 0, 0.15)',
    },
  },
  iconButtonStyles: {
    color: '#fff',
    marginLeft: '8px',
    padding: 0,
    transition: 'transform 0.3s ease',
    '&:hover': {
      transform: 'scale(1.1)',
    },
  },
  specializedNodesContainer: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '300px',
  },

  dropdownMenu: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    left: 0,
    display: 'none',
    flexDirection: 'column',
    alignItems: 'flex-start',
    minWidth: '220px',
    backgroundColor: '#1E2B3D',
    padding: '12px',
    borderRadius: '12px',
    boxShadow: '0 6px 12px rgba(0, 0, 0, 0.2)',
    zIndex: 10,
  },

  dropdownVisible: {
    display: 'flex',
  },
  dragClone: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '12px',
    color: '#fff',
    fontSize: '16px',
    opacity: 0.9,
    backgroundColor: theme.palette.secondary.main,
    pointerEvents: 'none',
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.2)',
    border: `2px solid ${theme.palette.secondary.light}`,
  },
  nodeContainer: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#fff',
    color: '#333',
    padding: '18px',
    borderRadius: '14px',
    width: '240px',
    border: '1px solid #E0E0E0',
    boxShadow: '0 6px 16px rgba(0, 0, 0, 0.08)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    '&:hover': {
      transform: 'translateY(-3px)',
      boxShadow: '0 8px 20px rgba(0, 0, 0, 0.12)',
    },
  },

  topbarStyles: {
    backgroundColor: theme.palette.secondary.main,
    padding: '12px',
    fontSize: '14px',
    borderRadius: '12px 12px 0 0',
    color: '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
    letterSpacing: '0.5px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    position: 'relative',
  },

  fieldContainer: {
    padding: '14px 0',
    color: 'black',
  },

  fieldWrapper: {
    marginBottom: '12px',
    borderRadius: '10px',
    transition: 'transform 0.2s ease',
    '&:hover': {
      transform: 'translateY(-2px)',
    },
  },

  fieldLabel: {
    display: 'block',
    marginBottom: '8px',
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#5f6368',
    letterSpacing: '0.2px',
  },

  inputField: {
    padding: '12px',
    fontSize: '14px',
    borderRadius: '8px',
    border: '1px solid #D1D1D1',
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: '#F7F7F7',
    transition: 'border-color 0.3s ease, box-shadow 0.3s ease',
    '&:focus': {
      borderColor: theme.palette.secondary.main,
      boxShadow: `0 0 0 2px ${theme.palette.secondary.light}`,
      outline: 'none',
    },
    '&:hover': {
      borderColor: theme.palette.secondary.light,
    },
  },

  deleteButton: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    width: '22px',
    height: '22px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    backgroundColor: 'rgba(244, 67, 54, 0.1)',
    color: theme.palette.error.main,
    transition: 'all 0.2s ease',
    opacity: 0.7,
    border: '1px solid transparent',
    '& .MuiSvgIcon-root': {
      fontSize: '16px',
    },
    '&:hover': {
      backgroundColor: 'rgba(244, 67, 54, 0.2)',
      color: theme.palette.error.dark,
      opacity: 1,
      transform: 'scale(1.1)',
      border: `1px solid ${theme.palette.error.light}`,
    },
  },
  textAreaField: {
    marginTop: '10px',
    marginBottom: '0px',
    padding: '12px',
    fontSize: '14px',
    borderRadius: '8px',
    border: '1px solid #D1D1D1',
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: '#F7F7F7',
    resize: 'none',
    overflow: 'hidden',
    minHeight: '40px',
    transition: 'border-color 0.3s ease, box-shadow 0.3s ease',
    '&:focus': {
      borderColor: theme.palette.secondary.main,
      boxShadow: `0 0 0 2px ${theme.palette.secondary.light}`,
      outline: 'none',
    },
    '&:hover': {
      borderColor: theme.palette.secondary.light,
    },
  },
  sliderFieldContainer: {
    marginTop: '15px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },

  sliderLabel: {
    fontSize: '14px',
    marginBottom: '10px',
    color: theme.palette.text.primary,
    fontWeight: 500,
  },

  slider: {
    color: theme.palette.secondary.main,
    width: '100%',
    '& .MuiSlider-thumb': {
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
      '&:hover, &.Mui-focusVisible': {
        boxShadow: '0 0 0 8px rgba(99, 102, 241, 0.16)',
      },
    },
    '& .MuiSlider-rail': {
      opacity: 0.5,
    },
  },

  currentValueText: {
    marginTop: '10px',
    fontSize: '14px',
    color: theme.palette.text.secondary,
    fontWeight: 500,
  },

  formattedMessageContainer: {
    textAlign: 'left',
    padding: '0',
    margin: '0',
  },
  successMessageTitle: {
    fontSize: '20px',
    display: 'block',
    marginBottom: '12px',
    color: theme.palette.success.main,
    textAlign: 'left',
    fontWeight: 600,
  },
  pipelineAnalysisLabel: {
    position: 'relative',
    fontSize: '16px',
    display: 'block',
    fontWeight: 'bold',
    textAlign: 'left',
    marginBottom: '8px',
    color: theme.palette.text.primary,
  },
  pipelineAnalysisList: {
    paddingLeft: '20px',
    marginBottom: '0px',
    fontSize: '14px',
    textAlign: 'left',
  },
  pipelineAnalysisListItem: {
    marginBottom: '8px',
    textAlign: 'left',
    lineHeight: 1.5,
  },
  snackbarPosition: {
    top: '80px !important',
    right: '15px !important',
  },
  submitButton: {
    backgroundColor: theme.palette.success.main,
    color: '#fff',
    padding: '12px 28px',
    borderRadius: '30px',
    fontSize: '16px',
    textTransform: 'none',
    boxShadow: '0 6px 16px rgba(76, 175, 80, 0.3)',
    transition: 'all 0.3s ease',
    fontWeight: 600,
    letterSpacing: '0.5px',
    marginTop: '0',
    '&:hover': {
      backgroundColor: theme.palette.success.dark,
      transform: 'translateY(-3px) scale(1.03)',
      boxShadow: '0 8px 20px rgba(76, 175, 80, 0.4)',
    },
    '&:active': {
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 8px rgba(76, 175, 80, 0.2)',
    },
  },
})
