export const toolbarStyles = theme => ({
  toolbarContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 20px',
    minHeight: '64px',
  },
  logoContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  draggableNodesContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    justifyContent: 'center',
    flexGrow: 1,
  },
  commonNodeStyles: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '16px',
    borderRadius: '8px',
    color: '#fff',
    padding: '8px 16px',
    transition: 'background-color 0.3s',
    cursor: 'pointer',
    position: 'relative',
    '&:hover': {
      backgroundColor: theme.palette.secondary.main,
    },
  },
  iconButtonStyles: {
    color: '#fff',
    marginLeft: '5px',
    padding: 0,
    transition: 'transform 0.2s',
  },
  specializedNodesContainer: {
    position: 'relative',
    marginLeft: '16px',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    left: 0,
    alignItems: 'left',
    backgroundColor: '#1E2B3D',
    padding: '10px',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    zIndex: 10,
    display: 'none',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '200px',
  },
  dropdownVisible: {
    display: 'flex',
  },
  dragClone: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '10px',
    color: '#fff',
    fontSize: '16px',
    opacity: 0.8,
    backgroundColor: theme.palette.secondary.main,
    pointerEvents: 'none',
  },
  nodeContainer: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#fff',
    color: '#333',
    padding: '15px',
    borderRadius: '12px',
    width: '220px',
    border: '1px solid #E0E0E0',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
  },

  topbarStyles: {
    backgroundColor: theme.palette.secondary.main,
    padding: '10px',
    borderRadius: '12px',
    color: '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
  },

  fieldContainer: {
    padding: '12px 0',
    color: 'black',
  },

  fieldWrapper: {
    marginBottom: '10px',
    borderRadius: '8px',
  },

  fieldLabel: {
    display: 'block',
    marginBottom: '6px',
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#5f6368',
  },

  inputField: {
    padding: '10px',
    fontSize: '14px',
    borderRadius: '6px',
    border: '1px solid #D1D1D1',
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: '#F7F7F7',
  },

  deleteButton: {
    position: 'absolute',
    top: '50%',
    right: '8px',
    transform: 'translateY(-50%)',
    color: theme.palette.error.main,
    padding: '4px',
    '&:hover': {
      color: theme.palette.error.dark,
    },
  },
})
