export const toolbarStyles = theme => ({
  toolbarContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 20px',
    minHeight: '64px',
  },
  logoContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  draggableNodesContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    justifyContent: 'center',
    flexGrow: 1,
  },
  commonNodeStyles: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '16px',
    borderRadius: '8px',
    color: '#fff',
    padding: '8px 16px',
    transition: 'background-color 0.3s',
    cursor: 'pointer',
    position: 'relative',
    '&:hover': {
      backgroundColor: theme.palette.secondary.main,
    },
  },
  iconButtonStyles: {
    color: '#fff',
    marginLeft: '5px',
    padding: 0,
    transition: 'transform 0.2s',
  },
  specializedNodesContainer: {
    position: 'relative',
    marginLeft: '16px',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    left: 0,
    alignItems: 'left',
    backgroundColor: '#1E2B3D',
    padding: '10px',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    zIndex: 10,
    display: 'none',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '200px',
  },
  dropdownVisible: {
    display: 'flex',
  },
  dragClone: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '10px',
    color: '#fff',
    fontSize: '16px',
    opacity: 0.8,
    backgroundColor: theme.palette.secondary.main,
    pointerEvents: 'none',
  },
})
